In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/india-districts-census-2011.csv")

df.head()

,District code,State name,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,94,588,71,101,172,74,10,84,15,1119
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,...,126,562,72,89,161,96,28,124,18,1066
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,46,122,15,22,37,20,14,34,17,242
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,56301,29935,18,...,27,114,12,18,30,19,3,22,7,214
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,163333,98391,556,...,78,346,35,50,85,59,8,67,12,629

In [3]:
df.columns

Index(['District code', 'State name', 'District name', 'Population', 'Male',
       'Female', 'Literate', 'Male_Literate', 'Female_Literate', 'SC',
       ...
       'Power_Parity_Rs_90000_150000', 'Power_Parity_Rs_45000_150000',
       'Power_Parity_Rs_150000_240000', 'Power_Parity_Rs_240000_330000',
       'Power_Parity_Rs_150000_330000', 'Power_Parity_Rs_330000_425000',
       'Power_Parity_Rs_425000_545000', 'Power_Parity_Rs_330000_545000',
       'Power_Parity_Above_Rs_545000', 'Total_Power_Parity'],
      dtype='object', length=118)

In [4]:
df.shape

(640, 118)

In [5]:
important_columns = [
    "District name",
    "State name",
    "Population",
    "Male",
    "Female",
    "Literate"
]

df = df[important_columns]

df.head()

  District name         State name  Population    Male  Female  Literate
0       Kupwara  JAMMU AND KASHMIR      870354  474190  396164    439654
1        Badgam  JAMMU AND KASHMIR      753745  398041  355704    335649
2   Leh(Ladakh)  JAMMU AND KASHMIR      133487   78971   54516     93770
3        Kargil  JAMMU AND KASHMIR      140802   77785   63017     86236
4         Punch  JAMMU AND KASHMIR      476835  251899  224936    261724

In [6]:
df.shape

(640, 6)

In [7]:
df.columns = [
    "district",
    "state",
    "population",
    "male_population",
    "female_population",
    "literate_population"
]

df.head()

,district,state,population,male_population,female_population,literate_population
0,Kupwara,JAMMU AND KASHMIR,870354,474190,396164,439654
1,Badgam,JAMMU AND KASHMIR,753745,398041,355704,335649
2,Leh(Ladakh),JAMMU AND KASHMIR,133487,78971,54516,93770
3,Kargil,JAMMU AND KASHMIR,140802,77785,63017,86236
4,Punch,JAMMU AND KASHMIR,476835,251899,224936,261724

In [8]:
df["literacy_rate"] = (
    df["literate_population"] / df["population"]
) * 100

In [9]:
df.head()

,district,state,population,male_population,female_population,literate_population,literacy_rate
0,Kupwara,JAMMU AND KASHMIR,870354,474190,396164,439654,50.514388
1,Badgam,JAMMU AND KASHMIR,753745,398041,355704,335649,44.530843
2,Leh(Ladakh),JAMMU AND KASHMIR,133487,78971,54516,93770,70.246541
3,Kargil,JAMMU AND KASHMIR,140802,77785,63017,86236,61.246289
4,Punch,JAMMU AND KASHMIR,476835,251899,224936,261724,54.887749

In [10]:
df["district"] = df["district"].str.lower().str.strip()
df["state"] = df["state"].str.lower().str.strip()

In [11]:
df.to_csv("../data/processed/district_master_dataset.csv", index=False)

In [12]:
df["gender_ratio"] = (df["female_population"] / df["male_population"]) * 1000

In [13]:
df["literacy_index"] = df["literacy_rate"] / 100

In [14]:
df["population_weight"] = df["population"] / df["population"].max()

In [15]:
df.head()

,district,state,population,male_population,female_population,literate_population,literacy_rate,gender_ratio,literacy_index,population_weight
0,kupwara,jammu and kashmir,870354,474190,396164,439654,50.514388,835.454143,0.505144,0.078693
1,badgam,jammu and kashmir,753745,398041,355704,335649,44.530843,893.636585,0.445308,0.068150
2,leh(ladakh),jammu and kashmir,133487,78971,54516,93770,70.246541,690.329361,0.702465,0.012069
3,kargil,jammu and kashmir,140802,77785,63017,86236,61.246289,810.143344,0.612463,0.012731
4,punch,jammu and kashmir,476835,251899,224936,261724,54.887749,892.961068,0.548877,0.043113

In [16]:
df.to_csv("../data/processed/district_master_dataset.csv", index=False)

In [17]:
df.shape

(640, 10)

In [18]:
df.isnull().sum()

district               0
state                  0
population             0
male_population        0
female_population      0
literate_population    0
literacy_rate          0
gender_ratio           0
literacy_index         0
population_weight      0
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
(df["male_population"] + df["female_population"] == df["population"]).all()

np.True_